/*
 * generated by Xtext
 */
package php.ware.scoping;

import static org.eclipse.xtext.scoping.Scopes.scopeFor;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;

import php.ware.entity.Feature;
import php.ware.entity.StructuralFeature;
import php.ware.web.CrudAction;

import com.google.common.collect.Iterables;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#scoping on
 * how and when to use it
 * 
 */
public class WebScopeProvider extends AbstractDeclarativeScopeProvider {

    public IScope scope_CrudAction_includedFeatures(final CrudAction ref,
            EReference eRef) {
        EList<Feature> features = ref.getType().getFeatures();
        Iterable<StructuralFeature> references = Iterables.filter(features,
                StructuralFeature.class);

        return scopeFor(references);
    }

    public IScope scope_CrudAction_excludedFeatures(final CrudAction ref,
            EReference eRef) {
        EList<Feature> features = ref.getType().getFeatures();
        Iterable<StructuralFeature> references = Iterables.filter(features,
                StructuralFeature.class);

        return scopeFor(references);
    }
}
